
Epoch 0:   0%|          | 0/998 [00:00<?, ?it/s]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name       | Type                     | Params
--------------------------------------------------------
0 | S1         | Sequential               | 1.6 K
1 | rsnn_block | LinearRecurrentContainer | 3.2 K
2 | output     | Sequential               | 41
3 | S2         | IFNode                   | 0
--------------------------------------------------------
4.9 K     Trainable params
0         Non-trainable params
4.9 K     Total params
0.020     Total estimated model params size (MB)

Epoch 0:   0%|          | 0/998 [00:00<?, ?it/s] -399.28253173828125 torch.Size([1293, 1, 40]) tensor(-0.1107, device='mps:0') tensor(0.1190, device='mps:0')
0.0 torch.Size([1293, 1, 40]) tensor(0., device='mps:0', grad_fn=<MinBackward1>) tensor(0., device='mps:0', grad_fn=<MaxBackward1>)
0.0 torch.Size([1293, 1, 40]) tensor(0., device='mps:0', grad_fn=<MinBackward1>) tensor(0., device='mps:0', grad_fn=<MaxBackward1>)
/Users/remi/Documents/PhD/NLP/SpikingExp/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py:44: Detected KeyboardInterrupt, attempting graceful shutdown...
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 2195, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 2177, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1489, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/remi/Documents/PhD/SpikingExp/spikingjelly_beat_detection.py", line 178, in <module>
    main()
  File "/Users/remi/Documents/PhD/SpikingExp/spikingjelly_beat_detection.py", line 174, in main
    trainer.fit(model)
  File "/Users/remi/Documents/PhD/NLP/SpikingExp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 754, in test
    return call._call_and_handle_interrupt(
  File "/Users/remi/Documents/PhD/NLP/SpikingExp/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/remi/Documents/PhD/NLP/SpikingExp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/Users/remi/Documents/PhD/NLP/SpikingExp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 937, in _run
    _verify_loop_configurations(self)
  File "/Users/remi/Documents/PhD/NLP/SpikingExp/lib/python3.9/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 42, in _verify_loop_configurations
    __verify_eval_loop_configuration(model, "test")
  File "/Users/remi/Documents/PhD/NLP/SpikingExp/lib/python3.9/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 110, in __verify_eval_loop_configuration
    raise MisconfigurationException(f"No `{step_name}()` method defined to run `Trainer.{trainer_method}`.")
